# Generated by Django 5.1.6 on 2025-02-22 07:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_customusermodel_pfp'),
    ]

    operations = [
    ]
