# Generated by Django 5.1.6 on 2025-02-22 11:19

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0003_auto_20250222_1551'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customusermodel',
            name='userId',
            field=models.CharField(default=uuid.uuid4, editable=False, max_length=36, primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='customusermodel',
            name='username',
            field=models.CharField(max_length=150, unique=True),
        ),
    ]
