# Generated by Django 5.1.6 on 2025-02-27 15:23

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0004_alter_customusermodel_userid_and_more'),
        ('otp_email', '0006_add_timestamps'),
    ]

    operations = [
        migrations.CreateModel(
            name='CustomEmailDevice',
            fields=[
                ('emaildevice_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='otp_email.emaildevice')),
            ],
            options={
                'abstract': False,
            },
            bases=('otp_email.emaildevice',),
        ),
    ]
