# Generated by Django 5.1.6 on 2025-02-28 15:28

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cook_list', '0002_cooklist_cooklist_cover_cooklist_cooklist_desc'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RemoveField(
            model_name='cooklist',
            name='cooklist_cover',
        ),
        migrations.RemoveField(
            model_name='cooklist',
            name='cooklist_desc',
        ),
        migrations.RemoveField(
            model_name='cooklist',
            name='cooklist_name',
        ),
        migrations.AlterField(
            model_name='cooklist',
            name='owner',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
