# Generated by Django 5.1.6 on 2025-03-04 01:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cook_list', '0003_remove_cooklist_cooklist_cover_and_more'),
        ('recipes', '0002_alter_recipeimage_image'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='cooklistitem',
            unique_together={('cooklist', 'recipe')},
        ),
    ]
