# Generated by Django 5.1.6 on 2025-02-25 03:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('interactions', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='like',
            old_name='liked_recipe',
            new_name='recipe',
        ),
        migrations.RenameField(
            model_name='share',
            old_name='shared_recipe',
            new_name='recipe',
        ),
    ]
