# Generated by Django 5.1.6 on 2025-02-27 15:23

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('interactions', '0002_rename_liked_recipe_like_recipe_and_more'),
        ('recipes', '0002_alter_recipeimage_image'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddConstraint(
            model_name='like',
            constraint=models.UniqueConstraint(fields=('user', 'recipe'), name='unique_like'),
        ),
    ]
